export const shoes = [
  {
    id: 1,
    flashNumber: 768,
    imageUrl: '../../assets/foot1.png',
    name: 'Nike Chuteira BOB Ano 2020',
    price: '789.90',
  },
  {
    id: 2,
    flashNumber: 44,
    imageUrl: '../../assets/foot2.png',
    name: 'Nike Zoom',
    price: '1540.90',
  },
  {
    id: 3,
    flashNumber: 2245,
    imageUrl: '../../assets/foot3.png',
    name: 'Jordan Washawabi ltd',
    price: '999.90',
  },
  {
    id: 4,
    flashNumber: 1456,
    imageUrl: '../../assets/foot4.png',
    name: 'DC Surfer Walker',
    price: '15698.90',
  },
  {
    id: 1,
    flashNumber: 768,
    imageUrl: '../../assets/foot1.png',
    name: 'Nike Chuteira BOB Ano 2020',
    price: '789.90',
  },
  {
    id: 2,
    flashNumber: 44,
    imageUrl: '../../assets/foot2.png',
    name: 'Nike Zoom',
    price: '1540.90',
  },
  {
    id: 3,
    flashNumber: 2245,
    imageUrl: '../../assets/foot3.png',
    name: 'Jordan Washawabi ltd',
    price: '999.90',
  },
  {
    id: 4,
    flashNumber: 1456,
    imageUrl: '../../assets/foot4.png',
    name: 'DC Surfer Walker',
    price: '15698.90',
  },
  {
    id: 1,
    flashNumber: 768,
    imageUrl: '../../assets/foot1.png',
    name: 'Nike Chuteira BOB Ano 2020',
    price: '789.90',
  },
  {
    id: 2,
    flashNumber: 44,
    imageUrl: '../../assets/foot2.png',
    name: 'Nike Zoom',
    price: '1540.90',
  },
  {
    id: 3,
    flashNumber: 2245,
    imageUrl: '../../assets/foot3.png',
    name: 'Jordan Washawabi ltd',
    price: '999.90',
  },
  {
    id: 4,
    flashNumber: 1456,
    imageUrl: '../../assets/foot4.png',
    name: 'DC Surfer Walker',
    price: '15698.90',
  },
  
]

export const footballBoots = [
{ 
  id: 1,
  flashNumber: 768,
  imageUrl: '../../assets/foot1.png',
  name: 'Nike PG 4 Football Grey Plaid',
  price: '500.00',
},
{ 
  id: 2,
  flashNumber: 256,
  imageUrl: '../../assets/foot1.png',
  name: 'Nike Air Max 97 Football Grey Light Thistle (W)',
  price: '798.00',
},
{ 
  id: 3,
  flashNumber: 467,
  imageUrl: '../../assets/foot1.png',
  name: 'Nike Signal D/MS/X Black Football Grey',
  price: '450.00',
},
{ 
  id: 4,
  flashNumber: 2452,
  imageUrl: '../../assets/foot1.png',
  name: 'Nike Air Max 270 Washed Coral Football Grey (W)',
  price: '846.99',
},
{ 
  id: 1,
  flashNumber: 768,
  imageUrl: '../../assets/foot1.png',
  name: 'Nike PG 4 Football Grey Plaid',
  price: '500.00',
},
{ 
  id: 2,
  flashNumber: 256,
  imageUrl: '../../assets/foot1.png',
  name: 'Nike Air Max 97 Football Grey Light Thistle (W)',
  price: '798.00',
},
{ 
  id: 3,
  flashNumber: 467,
  imageUrl: '../../assets/foot1.png',
  name: 'Nike Signal D/MS/X Black Football Grey',
  price: '450.00',
},
{ 
  id: 4,
  flashNumber: 2452,
  imageUrl: '../../assets/foot1.png',
  name: 'Nike Air Max 270 Washed Coral Football Grey (W)',
  price: '846.99',
},
]

export const sneakers = [
{ 
  id: 1,
  flashNumber: 768,
  imageUrl: '../../assets/foot1.png',
  name: 'Jordan 1 Retro High Tokyo Bio Hack',
  price: '1526.50',
},
{ 
  id: 2,
  flashNumber: 256,
  imageUrl: '../../assets/foot1.png',
  name: 'Jordan 5 Retro Alternate Bel-Air',
  price: '1240.90',
},
{ 
  id: 3,
  flashNumber: 467,
  imageUrl: '../../assets/foot1.png',
  name: 'adidas Yeezy 700 V3 Arzareth',
  price: '1862.30',
},
{ 
  id: 4,
  flashNumber: 2452,
  imageUrl: '../../assets/foot1.png',
  name: 'Jordan 12 Retro Black University Gold',
  price: '1385.99',
},
{ 
  id: 1,
  flashNumber: 768,
  imageUrl: '../../assets/foot1.png',
  name: 'Jordan 1 Retro High Tokyo Bio Hack',
  price: '1526.50',
},
{ 
  id: 2,
  flashNumber: 256,
  imageUrl: '../../assets/foot1.png',
  name: 'Jordan 5 Retro Alternate Bel-Air',
  price: '1240.90',
},
{ 
  id: 3,
  flashNumber: 467,
  imageUrl: '../../assets/foot1.png',
  name: 'adidas Yeezy 700 V3 Arzareth',
  price: '1862.30',
},
{ 
  id: 4,
  flashNumber: 2452,
  imageUrl: '../../assets/foot1.png',
  name: 'Jordan 12 Retro Black University Gold',
  price: '1385.99',
},

]
