export const shoes = [
  {
    id: 1,
    flashNumber: 768,
    imageUrl: '../../assets/foot1.png',
    name: 'Nike Chuteira BOB Ano 2020',
    price: '789.90',
  },
  {
    id: 2,
    flashNumber: 44,
    imageUrl: '../../assets/foot2.png',
    name: 'Nike Zoom',
    price: '1540.90',
  },
  {
    id: 3,
    flashNumber: 2245,
    imageUrl: '../../assets/foot3.png',
    name: 'Jordan Washawabi ltd',
    price: '999.90',
  },
  {
    id: 4,
    flashNumber: 1456,
    imageUrl: '../../assets/foot4.png',
    name: 'DC Surfer Walker',
    price: '15698.90',
  },
  {
    id: 1,
    flashNumber: 768,
    imageUrl: '../../assets/foot1.png',
    name: 'Nike Chuteira BOB Ano 2020',
    price: '789.90',
  },
  {
    id: 2,
    flashNumber: 44,
    imageUrl: '../../assets/foot2.png',
    name: 'Nike Zoom',
    price: '1540.90',
  },
  {
    id: 3,
    flashNumber: 2245,
    imageUrl: '../../assets/foot3.png',
    name: 'Jordan Washawabi ltd',
    price: '999.90',
  },
  {
    id: 4,
    flashNumber: 1456,
    imageUrl: '../../assets/foot4.png',
    name: 'DC Surfer Walker',
    price: '15698.90',
  },
  {
    id: 1,
    flashNumber: 768,
    imageUrl: '../../assets/foot1.png',
    name: 'Nike Chuteira BOB Ano 2020',
    price: '789.90',
  },
  {
    id: 2,
    flashNumber: 44,
    imageUrl: '../../assets/foot2.png',
    name: 'Nike Zoom',
    price: '1540.90',
  },
  {
    id: 3,
    flashNumber: 2245,
    imageUrl: '../../assets/foot3.png',
    name: 'Jordan Washawabi ltd',
    price: '999.90',
  },
  {
    id: 4,
    flashNumber: 1456,
    imageUrl: '../../assets/foot4.png',
    name: 'DC Surfer Walker',
    price: '15698.90',
  },
  
]